Href\hrefBundle\Entity\Structure:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  oneToMany:
    users:
      targetEntity: User
      mappedBy: structure


  fields:
    position: {type: string}
    symbol: {type: string}
    superior: {type: integer}
    level: {type: integer}