Href\hrefBundle\Entity\User:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    structure:
      targetEntity: Structure
      inversedBy: users






