structure_index:
    path:     /
    defaults: { _controller: "hrefBundle:Structure:index" }
    methods:  GET

structure_show:
    path:     /{id}/show
    defaults: { _controller: "hrefBundle:Structure:show" }
    methods:  GET

structure_new:
    path:     /new
    defaults: { _controller: "hrefBundle:Structure:new" }
    methods:  [GET, POST]

structure_edit:
    path:     /{id}/edit
    defaults: { _controller: "hrefBundle:Structure:edit" }
    methods:  [GET, POST]

structure_delete:
    path:     /{id}/delete
    defaults: { _controller: "hrefBundle:Structure:delete" }
    methods:  DELETE
